# Generated by Django 4.1 on 2022-08-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='point',
            field=models.IntegerField(),
        ),
    ]
