# Generated by Django 4.1 on 2022-08-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('dateofbirth', models.DateField()),
                ('contact', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
